name: Build Container Action
description: Build container images for a GitHub Actions workflow
author: Jackson Porter (JP)

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: box
  color: blue

# Define your inputs here.
inputs:
  config-json:
    description: The configuration JSON for the container image
    required: true
    default: '{}'
  config-file:
    description: The path to the configuration file for the container image
    required: false
    default: 'containers-build.toml'
  config-file-format:
    description: The format of the configuration file
    required: false
    default: 'toml'
  mode:
    description:
      The mode to run the action in, options are generate-matrix, build,
      combine-manifest, and push
    required: false
    default: 'build'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
