name: Build Container Action
description: Build container images for a GitHub Actions workflow
author: Jackson Porter (JP)

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: box
  color: blue

# Define your inputs here.
inputs:
  config:
    description: The configuration JSON for the container image
    required: true
    default: ''
  config-file:
    description: The path to the configuration file for the container image
    required: false
    default: 'containers-build.toml'
  config-format:
    description: The format of the configuration
    required: false
    default: 'rawConfig'
  config-file-format:
    description: The format of the configuration file
    required: false
    default: 'toml'
  mode:
    description: |
      The mode to run the action in. Options are:
      - generate-matrix: Generate the build matrix for the workflow
      - build: Build the container images
      - combine-manifest: Combine the manifests for multi-arch images
      - push: Push the container images to the registry
      - combine-build-outputs: Combine all build outputs into a single JSON object
    required: false
    default: 'build'
  build-name:
    description: The name of the build
    required: false
    default: 'build'
  build-output-artifact-name-prefix:
    description: The prefix to use for the build output artifact
    required: false
    default: 'build-containers-action-build-output'
  skip-step-summary:
    description: Whether to skip the step summary
    required: false
    default: 'false'
  build-outputs:
    description: Combined build outputs JSON for combine-manifests mode
    required: false
    default: ''

# Define your outputs here.
outputs:
  finalizedContainerConfig:
    description: The finalized container config
  jobMatrix:
    description: The job matrix for the build
  build-output-json:
    description: The build output for the build in JSON format
  build-output-json-path:
    description: The path to the build output JSON file

runs:
  using: node20
  main: dist/index.js
