name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Install project dependencies
        env:
          ENABLED_PACKAGE_MANAGERS: 'npm'
        run: mise run 'install'

      - name: Check Format
        id: npm-format-check
        run: mise run 'format-check'

      - name: Lint
        id: npm-lint
        run: mise run 'lint'

      - name: Test
        id: npm-ci-test
        run: mise run 'ci-test'

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
