name: Build Containers

on:
  workflow_call:
    inputs:
      config:
        type: string
        description: The config file contents
        default: ''
      config-file:
        type: string
        description: The path to the config file
        default: 'containers-build.toml'
      config-format:
        type: string
        description: The format of the config
        default: ''
      config-file-format:
        type: string
        description: The format of the config file
        default: 'toml'
      default-runner-label:
        type: string
        description: The default runner label to use for the build
        default: '["ubuntu-latest"]'

jobs:
  generate-matrix:
    runs-on: ${{ fromJson(inputs.default-runner-label) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: build-containers-action-matrix-generation
        uses: jacksonporter/build-containers-action@jp/v1dev
        with:
          config: ${{ inputs.config }}
          config-file: ${{ inputs.config-file }}
          config-file-format: ${{ inputs.config-file-format }}
          mode: generate-matrix
    outputs:
      windowsMatrix:
        ${{
        steps.build-containers-action-matrix-generation.outputs.windowsMatrix}}
      linuxMatrix:
        ${{
        steps.build-containers-action-matrix-generation.outputs.linuxMatrix}}

  # build-linux:
  #   needs:
  #     - generate-matrix
  #   strategy:
  #     matrix: ${{ fromJson(needs.generate-matrix.outputs.linuxMatrix) }}
  #   runs-on: ${{ matrix.ci.defaultRunnerLabels }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: test
  #       run: echo "${{ toJson(matrix) }}"

  build-windows:
    needs:
      - generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.windowsMatrix) }}
    runs-on: ${{ matrix.ci.defaultRunnerLabels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: build-containers-action-build
        uses: jacksonporter/build-containers-action@jp/v1dev
        with:
          config: ${{ matrix }}
          config-format: 'jobInclude'
          config-file-format: 'json'
          mode: 'build'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-containers-action-build
          path:
            ${{
            steps.build-containers-action-build.outputs.build-output-json-path
            }}
          retention-days: 1
