name: Build Containers

on:
  workflow_call:
    inputs:
      config:
        type: string
        description: The config file contents
        default: ''
      config-file:
        type: string
        description: The path to the config file
        default: 'containers-build.toml'
      config-format:
        type: string
        description: The format of the config file
        default: 'toml'
      default-runner-label:
        type: string
        description: The default runner label to use for the build
        default: '["ubuntu-latest"]'

jobs:
  generate-matrix:
    runs-on: ${{ fromJson(inputs.default-runner-label) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: build-containers-action-matrix-generation
        uses: jacksonporter/build-containers-action@jp/v1dev
        with:
          config: ${{ inputs.config }}
          config-file: ${{ inputs.config-file }}
          config-format: ${{ inputs.config-format }}
          mode: generate-matrix
    outputs:
      windowsMatrix:
        ${{ steps.build-containers-action-matrix-generation.outputs.windowsMatrix}}
      linuxMatrix:
        ${{ steps.build-containers-action-matrix-generation.outputs.linuxMatrix}}

  build-linux:
    needs:
      - generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.linuxMatrix) }}
    runs-on: ${{ matrix.ci.defaultRunnerLabels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: echo "${{ toJson(matrix) }}"

  build-windows:
    needs:
      - generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.windowsMatrix) }}
    runs-on: ${{ matrix.ci.defaultRunnerLabels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
